#
# Copyright (c) 2019 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
CONFIG_NCS_SAMPLES_DEFAULTS=y

CONFIG_SPIN_VALIDATE=n
CONFIG_PM=n
CONFIG_TIMESLICING=n

CONFIG_DK_LIBRARY=y

CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_UDC_DRIVER_LOG_LEVEL_WRN=y

CONFIG_USBD_HID_SUPPORT=y
CONFIG_USBD_LOG_LEVEL_WRN=y
CONFIG_USBD_HID_LOG_LEVEL_WRN=y

CONFIG_SAMPLE_USBD_MANUFACTURER="Nordic Semiconductor"
CONFIG_SAMPLE_USBD_PRODUCT="ESB dongle demo"
CONFIG_SAMPLE_USBD_SELF_POWERED=n
CONFIG_SAMPLE_USBD_MAX_POWER=50

CONFIG_NRFX_GPPI=y

CONFIG_NRFX_TIMER=y
CONFIG_LOG=y
